repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
-   repo: https://github.com/pre-commit/mirrors-pytest
    rev: v6.2.1
    hooks:
    -   id: pytest